// ================================
// Handles Tier Structure
// ================================
typedef struct{
	qboolean exists;
	qboolean permanent;
	qboolean hasCustomWeapons;
	qboolean hasActivated;
	qboolean alwaysAura;
	int index;
	int cameraType;
	int requirementPowerLevelCurrent;
	int requirementPowerLevelTotal;
	int requirementPowerLevelMax;
	int powerLevelDrain;
	int powerLevelTotalDrain;
	int powerLevelMaximumDrain;
	int bonusSpeed;
	int bonusZanzokenCost;
	int bonusPowerLevelCharge;
	int bonusZanzokenDistance;
	int bonusMeleeDefense;
	int bonusMeleeAttack;
	int bonusEnergyDefense;
	int bonusEnergyAttackDamage;
	int bonusEnergyAttackCost;
	char *name;
	char *iconPath;
	sfxHandle_t soundTransformFirst;
	sfxHandle_t soundTransform;
}tier;
